### ISSUE TITLE
libxml2.so error

### ISSUE THREAD

**Issue by chriseidhof** [swiftlang/swift-docker#17] opened 2015-12-14 13:25 UTC
I tried to get this to run:

```
docker pull swiftdocker/swift
docker run -i -t --name swiftfun swiftdocker/swift:latest /bin/bash
```

Then if I run `swift`, I get the following error:

```
/usr/bin/lldb: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory
```

Is this a known error? If not, I'll try to find the cause.

**Comment by chriseidhof** [comment] 2015-12-14 13:39
This could very well be a duplicate of issue #9 , in that case, feel free to close.

**Comment by swizzlr** [comment] 2015-12-15 20:07
This could be. Try compiling a program and see if that works; if so, it's a dupe of #9, if not, this is new.

The workaround is to use:

```
docker run --privileged -i -t --name swiftfun swiftdocker/swift:latest /bin/bash
```

**Comment by hamin** [comment] 2015-12-15 20:11
@chriseidhof yeah try what @swizzlr just suggested. We're still not quite sure what's causing this.

**Comment by swizzlr** [comment] 2015-12-17 01:41
@chriseidhof You were right, we needed libxml2 (also for Foundation). It's been resolved in master, could you try pulling again and seeing if it's improved?

**Comment by chriseidhof** [comment] 2015-12-17 09:20
Sorry, I was going to test the suggestion, but you guys are fast ;). Just tried the latest version in master, and it worked flawlessly.

Thanks for solving this, and thanks even more for doing this project :heart: .

**Comment by hamin** [comment] 2015-12-17 16:33
@chriseidhof awesome :) @swizzlr :+1:

**Closed as completed** 2015-12-17 16:33 UTC

**Comment by swizzlr** [comment] 2015-12-18 18:58
Excellent, glad to hear it!
